import ResponsiveAppBar from '@/components/MUIAppBar'

export const metadata = {
  title: 'Peter',
  description: 'Generated by Next.js'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <ResponsiveAppBar />
        {children}
      </body>
    </html>
  )
}
